object Versions {
    const val kotlinVersion = "1.5.30-RC"
    const val gradle = "4.0.0"
    const val gradlePlugin = "1.4.10"
    const val coreKTX = "1.6.10"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val fragmentKTX = "1.3.6"
    const val activityKTX = "1.3.1"
    const val recyclerView = "1.2.1"
    const val constrainLayout = "2.1.0"
    const val liveDataKTX = "2.3.1"
    const val lifecycleViewModelKTX = "2.3.1"
    const val java8 = "2.3.1"
    const val navigationFragmentKTX = "2.3.5"
    const val navigationUiKTX = "2.3.5"
    const val legacySupport = "1.0.0"
    const val coroutinesCore = "1.5.0"
    const val koin = "2.2.2"
    const val retrofit = "2.9.0"
    const val squareUp = "4.9.0"
    const val okCurl = "0.6.0"
    const val gson = "2.8.6"
    const val coil = "1.1.1"
    const val photoView = "2.3.0"
    const val timber = "4.7.1"
    const val androidxLifecycleViewModel = "2.2.0"

    //TESTING
    const val jUnit = "4.13.2"
    const val coreTesting = "2.1.0"
    const val coroutinesTest = "1.5.0"
    const val mockk = "1.10.6"
    const val mockWebServer = "4.9.1"
    const val extJunit = "1.1.2"
    const val espressoCore = "3.3.0"
    const val mockAndroid = "1.10.6"

}